from pathlib import Path
import re

EXT={'.js','.jsx','.ts','.tsx','.vue','.mjs','.cjs'}
SKIP={'node_modules','dist','build','.git','coverage','.next','.nuxt','.cursor','.codex','.agents','.agent','.claude','.idea','.vscode','migration','governance','handoff'}
GENERATED_MARKERS=('generated','auto-generated','autogenerated','do not edit')


def classify(rel,text):
    low=rel.lower(); head=text[:1000].lower()
    if any(m in head for m in GENERATED_MARKERS) or '/generated/' in low: return 'GENERATED'
    if any(x in low for x in ('/test/','/tests/','/__tests__/')) or re.search(r'\.(spec|test)\.[^.]+$',low): return 'TEST'
    if any(x in low for x in ('config.','/config/','vite.config','webpack.config','eslint.config')): return 'CONFIG'
    if any(x in low for x in ('/scripts/','/tooling/')): return 'TOOLING'
    return 'SOURCE'


def scan(root:Path):
    files=[]; findings=[]
    for p in root.rglob('*'):
        if not p.is_file() or p.suffix.lower() not in EXT: continue
        relp=p.relative_to(root)
        if any(x in relp.parts for x in SKIP): continue
        text=p.read_text(encoding='utf-8',errors='replace'); lines=text.count('\n')+1; rel=str(relp).replace('\\','/'); category=classify(rel,text)
        metrics={'file':rel,'classification':category,'lines':lines,'function_markers':len(re.findall(r'\b(?:function|=>|methods\s*:|computed\s*:)',text)),'http_markers':len(re.findall(r'\b(?:fetch|axios|\$http|request)\b',text))}
        files.append(metrics)
        if category!='SOURCE': continue
        if lines>=1200: findings.append({'id':f'CODE-{len(findings)+1:04d}','file':rel,'type':'GOD_FILE','severity':'critical','evidence':{'lines':lines}})
        elif lines>=600: findings.append({'id':f'CODE-{len(findings)+1:04d}','file':rel,'type':'LARGE_FILE','severity':'high','evidence':{'lines':lines}})
        if lines>=400 and metrics['http_markers']>=4: findings.append({'id':f'CODE-{len(findings)+1:04d}','file':rel,'type':'MIXED_DATA_ACCESS_UI','severity':'high','evidence':{'lines':lines,'http_markers':metrics['http_markers']}})
    source=[x for x in files if x['classification']=='SOURCE']; total=sum(x['lines'] for x in source); large=sum(1 for x in source if x['lines']>=600)
    score=max(0,100-min(70,large*8)-min(30,len([f for f in findings if f['type']=='MIXED_DATA_ACCESS_UI'])*5))
    return {'files':files,'findings':findings,'summary':{'files_scanned':len(files),'source_files_scored':len(source),'source_lines':total,'large_files':large,'score':score}}
